services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trpg
    ports:
      - "43306:3306"
    networks:
      - trpg-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trtory-backend-api
    container_name: trtory-container
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/trpg
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8080:8080"
    networks:
      - trpg-network

networks:
  trpg-network:
    name: trpg-network